<AnchorLayout>:
    anchor_x: 'center'
    anchor_y: 'center'
    BoxLayout:

        orientation: 'vertical'
        size_hint: 0.4, 0.75
        spacing: 10

        Label:
            text: "AnyStreak"
            font_size: 32
            color: 0.92, 0.92, 0.92   
            size_hint: 1.0, 0.5    

        Button:
            text: "[ + ] Start New"
            font_size: 40
            size_hint: 1.0, 0.2
 